POST http://localhost:8000/products
Content-Type: application/json

{
    "name": "My Product 3",
    "price": 100
}

###

GET http://localhost:8000/products HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDkyNTExOTYsInN1YiI6ImM1YWExMmM2LTExYTItNGRkNS05ODYyLTAyM2E0NmEwNDk2MCJ9.A1OfF-qKroNRmLirUhk8sAfsqU5cAhBzAYbqRraH8Mk